-- Migration 0012: roast template seed. ~6 per club + cross-cutting pools.
-- Slots resolve at render time; see SLOT REFERENCE. Boundaries per §12 enforced
-- on insert (blocked_terms) and by /roastkill at runtime. No LLM anywhere near this.

INSERT INTO roast_templates (body, target, scope, club_id, derby_id, conditions, severity, weight) VALUES
-- ============ ARSENAL (Archit, pick 1) ============
($B${loser} spent the first pick in the Premier League on ${loser_club} and just paid ${amount} for it. Frame it.$B$, 'LOSER','CLUB','arsenal',NULL,'{}',2,10),
($B${margin} goals. ${marquee} touched the ball eleven times and three of them were kick-offs.$B$, 'LOSER','CLUB','arsenal',NULL,'{"margin_min": 3}',3,10),
($B${manager} has had years and this is the tactical peak. ${loser} is paying ${amount} for the privilege of watching it.$B$, 'LOSER','MANAGER','arsenal',NULL,'{}',2,10),
($B$Bottled from the top again. ${loser_club} should come with a pressure warning.$B$, 'LOSER','CLUB','arsenal',NULL,'{}',2,10),
($B$Second place. Again. ${loser} could set his watch by it, if watches were won in May.$B$, 'LOSER','CLUB','arsenal',NULL,'{}',2,10),
($B$Mentality monsters. The mentality is fear and the monster is ${winner_club}.$B$, 'LOSER','CLUB','arsenal',NULL,'{"is_upset": true}',3,10),
-- ============ MAN CITY (Harshal, pick 2) ============
($B$115 charges and ${loser_club} still cannot beat ${winner_club}.$B$, 'LOSER','CLUB','man-city',NULL,'{}',2,10),
($B$No history before 2008 and no answer after 90 minutes. ${amount} to ${winner}.$B$, 'LOSER','CLUB','man-city',NULL,'{}',2,10),
($B$Listen carefully and you can hear the empty seats. ${loser} paid ${amount} to sit in one of the full ones.$B$, 'LOSER','CLUB','man-city',NULL,'{}',2,10),
($B$Bought the league, could not buy a goal against ${winner_club}.$B$, 'LOSER','CLUB','man-city',NULL,'{"is_upset": true}',3,10),
($B${manager} overthought exactly one game this year. It was this one.$B$, 'LOSER','MANAGER','man-city',NULL,'{}',2,10),
($B$Plastic club, plastic performance. ${winner} says thanks for the ${amount}.$B$, 'LOSER','CLUB','man-city',NULL,'{"margin_min": 3}',3,10),
-- ============ MAN UTD (Vedant, pick 3) ============
($B$A new era every eighteen months. This era costs ${loser} ${amount} a game.$B$, 'LOSER','CLUB','man-utd',NULL,'{}',2,10),
($B$Net spend of a nation-state, output of a midtable side. ${winner_club} took the points and the money.$B$, 'LOSER','CLUB','man-utd',NULL,'{}',2,10),
($B$The roof leaks, the midfield leaks more. ${score}. ${amount}.$B$, 'LOSER','CLUB','man-utd',NULL,'{}',2,10),
($B$Post-Ferguson season number whatever-this-is going well then, ${loser}?$B$, 'LOSER','CLUB','man-utd',NULL,'{}',2,10),
($B$The transfer committee met for six months to produce that. ${marquee} watched most of it happen.$B$, 'LOSER','CLUB','man-utd',NULL,'{"margin_min": 3}',3,10),
($B$Third pick in the Premier League. Third-rate evening. Poetry, ${loser}.$B$, 'LOSER','META','man-utd',NULL,'{"loser_pick": [3, 4]}',2,10),
-- ============ ASTON VILLA (Anmol, pick 4) ============
($B$One good season as an entire personality. ${loser_club} have reverted to type and ${loser} is paying for it.$B$, 'LOSER','CLUB','aston-villa',NULL,'{}',2,10),
($B$Fourth pick, fourth-best team, ${loser} acting surprised. The draft told you. The draft always tells you.$B$, 'LOSER','META','aston-villa',NULL,'{"loser_pick": [4]}',2,10),
($B$Delusions of size, performances of size small. ${amount} to ${winner}.$B$, 'LOSER','CLUB','aston-villa',NULL,'{}',2,10),
($B$${marquee} ran around a lot. Running around a lot is free. The ${amount} is not.$B$, 'LOSER','CLUB','aston-villa',NULL,'{}',1,10),
($B$Villa Park was loud for eleven minutes. The other seventy-nine belonged to ${winner_club}.$B$, 'LOSER','CLUB','aston-villa',NULL,'{"margin_min": 2}',2,10),
($B$${loser} picked the small club and got the small-club evening. Correct outcome, wrong wallet.$B$, 'LOSER','META','aston-villa',NULL,'{}',1,10),
-- ============ REAL MADRID (Vedant, pick 1) ============
($B${loser} used the first pick in La Liga on ${loser_club} and just lost to ${winner}'s fourth-rounder. ${amount}. That is what the money is for.$B$, 'LOSER','META','real-madrid',NULL,'{"opponent_draft_pick_worse_by": 2}',3,10),
($B$Where was ${marquee}? Was he even on the pitch, or is that just what the wages look like from row Z?$B$, 'LOSER','CLUB','real-madrid',NULL,'{}',2,10),
($B$Winning badly and calling it destiny only works in Europe, ${loser}. This was ${competition}.$B$, 'LOSER','CLUB','real-madrid',NULL,'{}',2,10),
($B$Theatrics from everyone, football from no one. ${winner_club} accept the donation of ${amount}.$B$, 'LOSER','CLUB','real-madrid',NULL,'{}',2,10),
($B$Galactico bloat, one working counter-attack, and a referee who finally watched the game. ${score}.$B$, 'LOSER','CLUB','real-madrid',NULL,'{"margin_min": 2}',2,10),
($B$Fifteen European Cups. Zero answers tonight. History does not defend set pieces, ${loser}.$B$, 'LOSER','CLUB','real-madrid',NULL,'{"is_upset": true}',3,10),
-- ============ BARCELONA (Anmol, pick 2) ============
($B$Pulled another lever and it landed on ${loser}. ${amount}, payable immediately, unlike the debt.$B$, 'LOSER','CLUB','barcelona',NULL,'{}',2,10),
($B$Sold the stadium, kept the problems. ${winner_club} thank the board for the entertainment.$B$, 'LOSER','CLUB','barcelona',NULL,'{}',2,10),
($B$La Masia cope is strong tonight. The kids are fine. It is the ${amount} that hurts.$B$, 'LOSER','CLUB','barcelona',NULL,'{}',2,10),
($B$Teenage hype cycles do not track back, ${loser}. ${score} does not lie.$B$, 'LOSER','CLUB','barcelona',NULL,'{"margin_min": 2}',2,10),
($B$More than a club. Specifically, more than a club that can defend. ${winner} collects.$B$, 'LOSER','CLUB','barcelona',NULL,'{}',2,10),
($B$The debt is over a billion and the high line is over everything. Priorities, ${loser}.$B$, 'LOSER','CLUB','barcelona',NULL,'{"margin_min": 3}',3,10),
-- ============ ATLETICO (Archit, pick 3) ============
($B$Parked the bus. The bus got towed. ${amount} to ${winner}.$B$, 'LOSER','CLUB','atletico',NULL,'{}',2,10),
($B$Ninety minutes of suffering, zero minutes of football. The suffering lost.$B$, 'LOSER','CLUB','atletico',NULL,'{}',2,10),
($B$The perpetual third wheel, finishing third in a two-horse race again. ${loser} knows the drill.$B$, 'LOSER','CLUB','atletico',NULL,'{}',2,10),
($B${manager} wept on the touchline. The touchline did not weep back.$B$, 'LOSER','MANAGER','atletico',NULL,'{}',2,10),
($B$Losing finals to ${winner_club} is tradition. Losing to them in ${competition} is just scheduling.$B$, 'LOSER','CLUB','atletico',NULL,'{}',2,10),
($B$Cholismo works until someone scores. Someone scored ${margin} time(s). Do the math, ${loser}.$B$, 'LOSER','CLUB','atletico',NULL,'{"margin_min": 2}',2,10),
-- ============ REAL BETIS (Harshal, pick 4) ============
($B$The small club did small-club things. ${loser} knew this when he spent the fourth pick on vibes.$B$, 'LOSER','META','real-betis',NULL,'{"loser_pick": [4]}',2,10),
($B$No ambition, no points, no money. The holy trinity of ${loser_club}.$B$, 'LOSER','CLUB','real-betis',NULL,'{}',2,10),
($B$Existing to embarrass bigger clubs, embarrassed by one instead. ${winner} sends regards and keeps the ${amount}.$B$, 'LOSER','CLUB','real-betis',NULL,'{"is_upset": true}',3,10),
($B$${marquee} tried. The other ten watched him try. ${score}.$B$, 'LOSER','CLUB','real-betis',NULL,'{}',1,10),
($B$Fourth-rounder does fourth-round things. The draft is never wrong, ${loser}.$B$, 'LOSER','META','real-betis',NULL,'{}',2,10),
($B$${manager} has seen it all before. So has everyone. That is the problem.$B$, 'LOSER','MANAGER','real-betis',NULL,'{}',1,10),
-- ============ BAYERN (Harshal, pick 1) ============
($B$Farmers league champions, harvested in ${competition}. ${winner_club} brought the combine.$B$, 'LOSER','CLUB','bayern',NULL,'{}',2,10),
($B$Buys every rival's best player and still loses the evenings that matter. ${amount}, ${loser}.$B$, 'LOSER','CLUB','bayern',NULL,'{"is_upset": true}',3,10),
($B$No competition all year, then competition arrives all at once. ${score}.$B$, 'LOSER','CLUB','bayern',NULL,'{"margin_min": 2}',2,10),
($B${marquee} scores for fun in Germany. Tonight was not in Germany, spiritually.$B$, 'LOSER','CLUB','bayern',NULL,'{}',2,10),
($B$First pick in the Bundesliga. First out of excuses. ${winner} collects ${amount}.$B$, 'LOSER','META','bayern',NULL,'{"loser_pick": [1]}',2,10),
($B$Still finding a way to lose in Europe. Some things are bigger than the club, ${loser}.$B$, 'LOSER','CLUB','bayern',NULL,'{"competitions": ["UCL"]}',2,10),
-- ============ LEVERKUSEN (Archit, pick 2, no UCL) ============
($B$Neverkusen. It is in the name, ${loser}. You picked it anyway.$B$, 'LOSER','CLUB','leverkusen',NULL,'{}',2,10),
($B$One good season. ${loser} bought the sequel and the sequel is direct-to-video.$B$, 'LOSER','CLUB','leverkusen',NULL,'{}',2,10),
($B$Not even in the Champions League and still finding ways to lose to teams that are. Range, ${loser}.$B$, 'LOSER','CLUB','leverkusen',NULL,'{}',2,10),
($B$Second-round pick, second-tier evening. The market has spoken: ${amount}.$B$, 'LOSER','META','leverkusen',NULL,'{"loser_pick": [2]}',2,10),
($B$The invincible season gets further away every week. ${winner_club} just added mileage.$B$, 'LOSER','CLUB','leverkusen',NULL,'{}',2,10),
($B${marquee} left or stayed, it hardly matters. The result is the same and so is the bill.$B$, 'LOSER','CLUB','leverkusen',NULL,'{}',1,10),
-- ============ DORTMUND (Anmol, pick 3) ============
($B$Bayern's feeder club delivered on schedule. ${winner} says the produce was excellent.$B$, 'LOSER','CLUB','dortmund',NULL,'{}',2,10),
($B$Selling club, selling performance. Everything must go, including the ${amount}.$B$, 'LOSER','CLUB','dortmund',NULL,'{}',2,10),
($B$The yellow wall is a substitute for trophies. Eighty thousand witnesses, zero points.$B$, 'LOSER','CLUB','dortmund',NULL,'{}',2,10),
($B$Choked in another race that mattered. ${loser} has seen this film and paid for the sequel.$B$, 'LOSER','CLUB','dortmund',NULL,'{"margin_min": 2}',2,10),
($B$Develop the talent, sell the talent, lose to the talent. The Dortmund cycle, billed at ${amount}.$B$, 'LOSER','CLUB','dortmund',NULL,'{}',2,10),
($B$${marquee} will look great in Munich next year. Everyone knows it. Especially ${loser}.$B$, 'LOSER','CLUB','dortmund',NULL,'{}',2,10),
-- ============ RB LEIPZIG (Vedant, pick 4) ============
($B$A club invented in 2009 by an energy drink company just took ${amount} off ${loser}.$B$, 'LOSER','CLUB','rb-leipzig',NULL,'{}',2,10),
($B$No fans, no history, no problem beating ${loser_club}. ${score}.$B$, 'LOSER','CLUB','rb-leipzig',NULL,'{}',2,10),
($B$The 50+1 workaround worked around ${loser} completely tonight.$B$, 'LOSER','CLUB','rb-leipzig',NULL,'{}',2,10),
($B$Corporate football with a corporate result: efficient, soulless, ${amount} to ${winner}.$B$, 'LOSER','CLUB','rb-leipzig',NULL,'{}',2,10),
($B$Fourth pick, and it shows. The spreadsheet said value. The spreadsheet lied, ${loser}.$B$, 'LOSER','META','rb-leipzig',NULL,'{"loser_pick": [4]}',2,10),
($B$${marquee} pressed for ninety minutes and pressed exactly nothing that mattered.$B$, 'LOSER','CLUB','rb-leipzig',NULL,'{}',1,10),
-- ============ INTER (Anmol, pick 1) ============
($B$First pick in Serie A, first to fold. ${loser} drafted prestige and got paperwork.$B$, 'LOSER','META','inter',NULL,'{"loser_pick": [1]}',2,10),
($B$Bottling finals is the tradition. Tonight they bottled something smaller, earlier, cheaper. Still ${amount}.$B$, 'LOSER','CLUB','inter',NULL,'{}',2,10),
($B$A retirement league with retirement defending. ${winner_club} accept the pension contribution.$B$, 'LOSER','CLUB','inter',NULL,'{}',2,10),
($B$One good year at a time, and this is not the year. The books say ${amount} outgoing.$B$, 'LOSER','CLUB','inter',NULL,'{}',2,10),
($B${marquee} carries the attack the way ${loser} carries the group chat: alone, and losing.$B$, 'LOSER','CLUB','inter',NULL,'{}',2,10),
($B$The accounting is creative. The defending was fictional. ${score}.$B$, 'LOSER','CLUB','inter',NULL,'{"margin_min": 2}',2,10),
-- ============ NAPOLI (Vedant, pick 2) ============
($B$One title a generation. This generation is watching ${winner_club} take ${amount} off them.$B$, 'LOSER','CLUB','napoli',NULL,'{}',2,10),
($B$Maradona nostalgia is forty years old. The defending is older. ${score}.$B$, 'LOSER','CLUB','napoli',NULL,'{}',2,10),
($B$Sells everyone who plays well, then wonders why nobody plays well. ${loser} funded the cycle.$B$, 'LOSER','CLUB','napoli',NULL,'{}',2,10),
($B$${marquee} ran himself into the ground. The ground sends its regards and keeps the points.$B$, 'LOSER','CLUB','napoli',NULL,'{}',1,10),
($B$Second pick, second-best on the night, second to the money. ${winner} thanks you.$B$, 'LOSER','META','napoli',NULL,'{"loser_pick": [2]}',2,10),
($B$The scudetto lives in Naples. Tonight it watched ${winner_club} leave with ${amount}.$B$, 'LOSER','CLUB','napoli',NULL,'{"margin_min": 2}',2,10),
-- ============ ROMA (Harshal, pick 3) ============
($B$Totti nostalgia cannot defend a counter. ${score} cannot be appealed to history.$B$, 'LOSER','CLUB','roma',NULL,'{}',2,10),
($B$Perpetual almost. Almost defended, almost scored, fully paid ${amount}.$B$, 'LOSER','CLUB','roma',NULL,'{}',2,10),
($B$Second in a two-club city, second-best on the night. Consistency, ${loser}.$B$, 'LOSER','CLUB','roma',NULL,'{}',2,10),
($B$The manager carousel spins again. Same riders, same drop, ${amount} admission.$B$, 'LOSER','CLUB','roma',NULL,'{}',2,10),
($B$${marquee} did tricks. Tricks are free. Points cost ${amount} and went to ${winner}.$B$, 'LOSER','CLUB','roma',NULL,'{}',1,10),
($B$Third pick, third act of the same tragedy. ${loser} knows the ending by heart.$B$, 'LOSER','META','roma',NULL,'{"loser_pick": [3]}',2,10),
-- ============ JUVENTUS (Archit, pick 4, no UCL) ============
($B$The asterisk played tonight. So did ${winner_club}. Only one of them scored.$B$, 'LOSER','CLUB','juventus',NULL,'{}',2,10),
($B$Not even in Europe this season and still losing to teams preparing for it. ${amount}.$B$, 'LOSER','CLUB','juventus',NULL,'{}',2,10),
($B$The Old Lady is declining and the nursing fees are ${amount} a night, ${loser}.$B$, 'LOSER','CLUB','juventus',NULL,'{}',2,10),
($B$Fourth pick, and it cost like a first. The draft sends its condolences and keeps the change.$B$, 'LOSER','META','juventus',NULL,'{"loser_pick": [4]}',2,10),
($B$Calciopoli was decades ago. The losing is right now. ${score}.$B$, 'LOSER','CLUB','juventus',NULL,'{"margin_min": 2}',2,10),
($B$${marquee} is the future. The future lost ${amount} to the present.$B$, 'LOSER','CLUB','juventus',NULL,'{}',1,10),
-- ============ MARGIN pool (thrashing) ============
($B${margin} goals. That is not a defeat, it is an itemised bill, and ${loser} is paying every line.$B$, 'LOSER','MARGIN',NULL,NULL,'{"margin_min": 4}',3,10),
($B$Four-goal margin. The fixture doubled and so did the humiliation. ${amount}, ${loser}. Read it twice.$B$, 'LOSER','MARGIN',NULL,NULL,'{"margin_min": 4}',3,10),
($B${winner} did not just win, he redecorated. ${loser_club} are now ${amount} worth of wallpaper.$B$, 'WINNER','MARGIN',NULL,NULL,'{"margin_min": 4}',3,10),
($B${margin}–0 on talent, ${amount}–0 on money. Some nights the spreadsheet and the scoreline agree.$B$, 'NEUTRAL','MARGIN',NULL,NULL,'{"margin_min": 4}',3,10),
-- ============ META pool (draft shame, streaks, tables) ============
($B${loser} spent the ${loser_pick} pick on ${loser_club} and lost to a ${winner_pick} rounder. The draft order is never wrong. ${loser} is.$B$, 'LOSER','META',NULL,NULL,'{"opponent_draft_pick_worse_by": 2}',3,10),
($B${streak}. At what point does ${loser} accept this is just who he is.$B$, 'LOSER','META',NULL,NULL,'{"is_streak": true}',3,10),
($B${loser} is now ${loser_net} down and still telling people ${loser_club} are a big club.$B$, 'LOSER','META',NULL,NULL,'{}',2,10),
($B${h2h}. Read it again slowly, ${loser}. Then pay the ${amount}.$B$, 'LOSER','META',NULL,NULL,'{}',2,10),
($B$Rank ${rank} with ${loser_club}. The table has opinions and it has shared them.$B$, 'LOSER','META',NULL,NULL,'{}',1,10),
($B${owed} between these two this season and it keeps flowing one way. Hydrology, ${loser}.$B$, 'LOSER','META',NULL,NULL,'{}',2,10),
-- ============ SHOOTOUT pool ============
($B$Won on penalties, which counts as a win and feels like theft. ${loser} paid ${amount} for extra time he will never get back.$B$, 'LOSER','META',NULL,NULL,'{"shootout": true}',2,10),
($B$One hundred and twenty minutes could not separate them. The shootout could. ${winner} thanks the lottery and keeps the ${amount}.$B$, 'WINNER','META',NULL,NULL,'{"shootout": true}',2,10),
($B$Penalties. The cruellest way to lose ${amount}, chosen democratically by two teams who refused to score.$B$, 'NEUTRAL','META',NULL,NULL,'{"shootout": true}',2,10),
-- ============ DERBY pools ============
($B$El Clásico and ${loser_club} turned up with that. Somewhere an investor is asking for a refund.$B$, 'LOSER','DERBY',NULL,'el-clasico','{}',3,10),
($B$Ninety minutes of the biggest club game on earth and ${loser} got ninety minutes of this. ${amount}.$B$, 'LOSER','DERBY',NULL,'el-clasico','{}',2,10),
($B$Der Klassiker. ${loser_club} played like the undercard and got paid like it too: nothing, plus a ${amount} bill.$B$, 'LOSER','DERBY',NULL,'klassiker','{}',3,10),
($B$Bayern against Dortmund is a rivalry the way a bank is a rival to a wallet. ${winner} made the withdrawal.$B$, 'WINNER','DERBY',NULL,'klassiker','{}',2,10),
($B$Manchester Derby. ${loser} owns half the city and none of the points. ${amount} across town.$B$, 'LOSER','DERBY',NULL,'manchester-derby','{}',3,10),
($B$Same city, same night, different sport apparently. ${winner_club} played football. ${loser_club} attended.$B$, 'LOSER','DERBY',NULL,'manchester-derby','{}',2,10),
($B$Derby d'Italia. ${loser} brought history to a football match and history did not show up.$B$, 'LOSER','DERBY',NULL,'derby-d-italia','{}',3,10),
($B$Madrid Derby. Losing to ${winner_club} is tradition for ${loser_club}. Some traditions cost ${amount}.$B$, 'LOSER','DERBY',NULL,'madrid-derby','{}',2,10);
